app:
  ~chart: app
  probesPath: /healthz
  imagePackage: app
  volumes:
    - name: repos
      emptyDir: {}
    - name: tmp
      emptyDir: {}
  volumeMounts:
    - mountPath: /app/repos
      name: repos
    - mountPath: /tmp
      name: tmp
  envFrom:
    - secretRef:
        name: app
    - configMapRef:
        name: app
